use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/categories",
        "merchandise",
        "catalog.categories.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/categories",
        "merchandise",
        "catalog.categories.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/categories/{categoryId}",
        "merchandise",
        "catalog.categories.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/categories/{categoryId}",
        "merchandise",
        "catalog.categories.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/products",
        "merchandise",
        "catalog.products.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/products",
        "merchandise",
        "catalog.products.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "catalog.products.management.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "catalog.products.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/products/{productId}",
        "merchandise",
        "catalog.products.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/spus",
        "merchandise",
        "catalog.spus.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/spus",
        "merchandise",
        "catalog.spus.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/spus/{spuId}",
        "merchandise",
        "catalog.spus.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/spus/{spuId}/publish",
        "merchandise",
        "catalog.spus.publish",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/spus/{spuId}/archive",
        "merchandise",
        "catalog.spus.archive",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/skus",
        "merchandise",
        "catalog.skus.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/skus",
        "merchandise",
        "catalog.skus.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/skus/{skuId}",
        "merchandise",
        "catalog.skus.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/skus/{skuId}",
        "merchandise",
        "catalog.skus.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/attributes",
        "merchandise",
        "catalog.attributes.management.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/attributes",
        "merchandise",
        "catalog.attributes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/category_attributes",
        "merchandise",
        "catalog.categoryAttributes.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/category_attributes",
        "merchandise",
        "catalog.categoryAttributes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/category_attributes/{bindingId}",
        "merchandise",
        "catalog.categoryAttributes.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/catalog/category_attributes/{bindingId}",
        "merchandise",
        "catalog.categoryAttributes.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/catalog/price_lists",
        "merchandise",
        "catalog.priceLists.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/catalog/price_lists",
        "merchandise",
        "catalog.priceLists.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/catalog/price_lists/{priceListId}",
        "merchandise",
        "catalog.priceLists.update",
    ),
];

pub fn backend_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
