//! Generated gateway bootstrap for sdkwork-merchandise.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use sdkwork_merchandise_service_host::ShopServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<ShopServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_merchandise_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_merchandise_backend_api::gateway_mount(host.clone()).await);
    ApplicationAssembly { router }
}
